# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Custard Run
description: Runs "custard.ts run" against all the paths, for the given command

inputs:
  config-file:
    description: Path to the custard config file.
    default: .github/config.jsonc
  custard-command:
    description: The custard command to run (defined in config.jsonc).
    required: true
  paths:
    description: Comma-separated package paths instead of git diff.
  custard-version:
    description: Custard version to install.
    default: v0.1.0
  install-path:
    description: Path to install the Custard script to.
    default: custard.ts

runs:
  using: composite
  steps:
    - name: Run command
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
      with:
        # WIP: manual fork of map-run due to invocation issues.
        script: |
            await exec.exec("pwd");
            await exec.exec("ls");

            const cmd = "${{ inputs.custard-command }}";
            const paths = ${{ inputs.paths }};
            if (paths.length === 0) {
              core.notice("No paths detected. Nothing to do.")
            }

            let failed = [];
            for (const path of paths) {
              try {
                const status = await exec.exec("node", ["${{ inputs.install-path }}", "run", "${{ inputs.config-file }}", "${{ inputs.custard-command }}", path]);
                if (status === 0) {
                  console.log(`✅ [${path}]: ${cmd}`);
                } else {
                  console.log(`⛔️ [${path}]: ${cmd} (exit code ${status})`);
                  failed.push(path);
                }
              } catch (e) {
                console.log(`❌ [${path}]: ${cmd} failed`);
                console.error(e)
                failed.push(path);
              }
            }
            console.log("=== Summary ===");
            console.log(`  Passed: ${paths.length - failed.length}`);
            console.log(`  Failed: ${failed.length}`);
            if (failed.length > 0) {
              core.setFailed(`Failed '${cmd}' on: ${failed.join(', ')}`);
            }
