# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Find affected
description: Finds the affected packages.

inputs:
  config-file:
    description: Path to the custard config file.
    required: true
  head-sha:
    description: The commit sha of the head where the changes live.
    default: HEAD
  main-sha:
    description: The commit sha of the main branch to be compared to.
    default: origin/main
  paths:
    description: Comma-separated package paths instead of git diff.
  custard-version:
    description: Custard version to install.
    default: v0.0.10
  install-path:
    description: Path to install the Custard script to.
    default: custard.ts
  checkout-path:
    description: Path to check out directory to find affected packages
    default: repo-checkout

outputs:
  paths:
    description: The affected paths as a JSON list.
    value: ${{ steps.custard.outputs.paths }}
  num-paths:
    description: The number of affected paths.
    value: ${{ steps.custard.outputs.num-paths }}
  ci-setups:
    description: The CI setup configurations for the affected packages.
    value: ${{ steps.custard.outputs.ci-setups }}

runs:
  using: composite
  steps:
    - name: Setup Custard
      uses: glasnt/trifle/actions/steps/setup-custard@debugging-matchPackages
      with:
        install-path: ${{ inputs.install-path }}
        version: debugging-matchPackages
    # Find the affected packages.
    - name: Checkout the commit history
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        ref: ${{ inputs.head-sha }}
        fetch-depth: 0 # fetch the entire branch history to find diffs
        path: ${{ inputs.checkout-path }}
    - name: Get diffs from main and the PR
      shell: bash
      run: |
        if [[ -n "$PATHS" ]]; then
          # If paths are explicitly provided, use them.
          echo "$PATHS" \
            | sed 's/ *, */\n/g' \
            | sed 's/$/\/diff/' \
            | tee diffs.txt
        else
          # Otherwise, use git diff.
          git -C ${{ inputs.checkout-path }} --no-pager diff --name-only $HEAD $MAIN \
            | tee diffs.txt
        fi
      env:
        HEAD: ${{ inputs.head-sha }}
        MAIN: ${{ inputs.main-sha }}
        PATHS: ${{ inputs.paths }}
    - name: Find affected packages
      id: custard
      shell: bash
      working-directory: ${{ inputs.checkout-path }}
      run: |
        node ${{ inputs.install-path }} affected ${{ inputs.checkout-path }}/${{ inputs.config-file }} diffs.txt | tee paths.txt
        PATHS=$(jq -Rcn '[inputs]' paths.txt)
        echo "paths=$PATHS" >> $GITHUB_OUTPUT
        echo "num-paths=$(echo $PATHS | jq length)" >> $GITHUB_OUTPUT
